# Turn on validation, so we can use import:
version: ~> 1.0

jdk:
- openjdk8
import: land-of-apps/land-of-apps:travis/java-imports.yml

script:
- ./gradlew clients:unitTest -PignoreFailures=true
- ./gradlew streams:unitTest -PignoreFailures=true
- ./gradlew connect:unitTest -PignoreFailures=true
- ./gradlew generator:unitTest -PignoreFailures=true
- ./gradlew log4j-appender:unitTest -PignoreFailures=true
- ./gradlew tools:unitTest -PignoreFailures=true
