# Turn on validation, so we can use import:
version: ~> 1.0

jdk:
- openjdk8
import: land-of-apps/land-of-apps:travis/java-imports.yml

script:
- travis_wait 75 ./gradlew unitTest -PignoreFailures=true
